version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: ./containers/nginx
    restart: 'always'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${REPO_DIR}:/www
      - ./containers/nginx/vhosts:/etc/nginx/conf.d
    links:
      - php74
      - mysql

  php74:
    container_name: php74
    build:
      context: ./containers/php/74
    restart: 'always'
    volumes:
      - ${REPO_DIR}:/www
      - ./containers/php/74/php.ini:/usr/local/etc/php/conf.d/php.ini

  mysql:
    container_name: mysql
    build:
      context: ./containers/mysql
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: