version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: ./containers/nginx
    restart: 'always'
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${REPO_DIR}:/www
      - ./containers/nginx/vhosts:/etc/nginx/conf.d
    links:
      - php74
      - mysql

  php70:
    container_name: php70
    build:
      context: ./containers/php/70
    restart: 'always'
    volumes:
      - ${REPO_DIR}:/www
      - ./containers/php/70/php.ini:/usr/local/etc/php/conf.d/php.ini

  php71:
    container_name: php71
    build:
      context: ./containers/php/71
    restart: 'always'
    volumes:
      - ${REPO_DIR}:/www
      - ./containers/php/71/php.ini:/usr/local/etc/php/conf.d/php.ini

  php72:
    container_name: php72
    build:
      context: ./containers/php/72
    restart: 'always'
    volumes:
      - ${REPO_DIR}:/www
      - ./containers/php/72/php.ini:/usr/local/etc/php/conf.d/php.ini

  php73:
    container_name: php73
    build:
      context: ./containers/php/73
    restart: 'always'
    volumes:
      - ${REPO_DIR}:/www
      - ./containers/php/73/php.ini:/usr/local/etc/php/conf.d/php.ini

  php74:
    container_name: php74
    build:
      context: ./containers/php/74
    restart: 'always'
    volumes:
      - ${REPO_DIR}:/www
      - ./containers/php/74/php.ini:/usr/local/etc/php/conf.d/php.ini

  mysql:
    container_name: mysql
    build:
      context: ./containers/mysql
    restart: 'always'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: